### ISSUE TITLE
Not finding "related" service for a pod

### ISSUE THREAD

**Issue by lhankinsgdl** [sunny0826/kubectl-sniffer#2]
I have a service:
```
Name:                     kubeview-nginx
Namespace:                kubeview
Labels:                   app=kubeview
                          app.kubernetes.io/managed-by=Helm
                          chart=kubeview-1.0.0
                          heritage=Helm
                          release=kubeview
Annotations:              meta.helm.sh/release-name: kubeview
                          meta.helm.sh/release-namespace: kubeview
Selector:                 app=kubeview-nginx
Type:                     LoadBalancer
IP:                       10.134.0.113
IP:                       <redacted>
LoadBalancer Ingress:    <redacted>
Port:                     http  80/TCP
TargetPort:               http/TCP
NodePort:                 http  30445/TCP
Endpoints:                10.4.6.145:80
Port:                     https  443/TCP
TargetPort:               https/TCP
NodePort:                 https  30345/TCP
Endpoints:                10.4.6.145:443
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>
```

...that I think should be counted as "related" this pod:

```
Name:         kubeview-nginx-6b64cdc4f5-2zg86
Namespace:    kubeview
Priority:     0
Node:        <redacted>
Start Time:   Thu, 11 Mar 2021 12:54:34 -0500
Labels:       app=kubeview-nginx
              pod-template-hash=6b64cdc4f5
              role=nginx
<snip>
```

Is there something we should do to make them link up?

(Neat plugin, thanks!)

**Comment by sunny0826** [comment]
Here "related" means related k8s resources, such as: `ingress`, `service`, `HPA`, etc.

I understand that what you describe is more of a pod info.

**Comment by lhankinsgdl** [comment]
Ah, ok.  I may be misunderstanding what causes a pod to be "related" to a service.  In this case, the service has a selector of `app=kubeview-nginx` and the pod has that label.  Is there another criteria that makes them related?

**Comment by sunny0826** [comment]
@lhankinsgdl The currently supported label are: `app`, `release`, `k8s-app`,` app.kubernetes.io/name`, and custom labels will be supported later.
Also, English is not my native language, so maybe my description is confusing, can you help me to describe the plugin better?

**Comment by davidcollom** [comment]
I think that @lhankinsgdl had the same/similar assumption as myself.
Where related would be that label selectors for a service for an example match the pod in question.

What in fact the plugin is doing is looking for resources sharing the same/similar labels as the pod its self.
