### ISSUE TITLE
Plugin fails to install on Apple Silicon (ARM / M1)

### ISSUE THREAD

**Issue by sammcj** [sunny0826/kubectl-sniffer#7]
When trying to install this plug in my Macbook air (with M1 processor) I get the following error:

```
kubectl krew install pod-lens
Updated the local copy of plugin index.
Installing plugin: pod-lens
W0829 13:36:34.204050   10582 install.go:164] failed to install plugin "pod-lens": plugin "pod-lens" does not offer installation for this platform
F0829 13:36:34.204109   10582 root.go:79] failed to install some plugins: [pod-lens]: plugin "pod-lens" does not offer installation for this platform
```

Would it be possible to to add a `darwin/arm64` build target?

**Comment by sunny0826** [comment]
Thanks for your feedback and contribution!

**Comment by sunny0826** [comment]
I released [v0.2.1](https://github.com/sunny0826/kubectl-pod-lens/releases/tag/v0.2.1), but `pod-lens_darwin_arm64` was not generated. I will fix it.

**Comment by sammcj** [comment]
Oh interesting! Thank you

**Comment by sunny0826** [comment]
done, the [upstream configuration](https://github.com/kubernetes-sigs/krew-index/pull/1492) has also been updated.   
 @sammcj I don't have Macs with M1-chip, so please try the newest version.

**Comment by sammcj** [comment]
Tested - works! Thank you @sunny0826 !
